defaults: &defaults
  card_roles:
    1:  "Straight Flush"
    2:  "Four-of-a-Kind"
    3:  "Full House"
    4:  "Flash"
    5:  "Straight"
    6:  "Three-of-a-Kind"
    7:  "Two Pair"
    8:  "Oner Pair"
    9:  "High Card"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults